id: '17153290317420.029143842590584557'
kind: workflow
name: handleTableRowSelect
nameConfigured: true
steps:
  - id: '17156723962600.2111338065987396'
    type: putInStore
    name: updateSelectedRowsState
    params:
      - type: name
        value: '17155870595720.15997165618350517'
        valueType: string
      - type: value
        value: '{{params.selectedRows}}'
        valueType: interpolatedValue
        interpolationType: code
      - type: producible
        value: true
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
    nameConfigured: true
  - id: '17153374362490.8324175301338119'
    type: executeAction
    name: updateAnalytics
    params:
      - type: action
        value: '17153373221410.6418544338443553'
        valueType: custom
      - type: isActionsLibraryCall
        value: false
        valueType: custom
      - type: customParams
        value: ./updateAnalytics-customParams.js
        valueType: interpolatedValue
        interpolationType: code
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
    nameConfigured: true
  - id: '17155791548230.7455558565983171'
    type: executeAction
    name: updateChart
    params:
      - type: action
        value: '17153491096460.13907861102792696'
        valueType: custom
      - type: isActionsLibraryCall
        value: false
        valueType: custom
      - type: customParams
        value: ./updateChart-customParams.js
        valueType: interpolatedValue
        interpolationType: code
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
    nameConfigured: true
mode: manual
modeConfigured: true
parentPageId: '1'
config:
  shouldConfirm: false
  confirmMessage: >-
    Are you sure you'd like to proceed with
    "{{actions.handleTableRowSelect.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.handleTableRowSelect.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.handleTableRowSelect.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
selected: true
configured: true
parentId: '17153302404560.9648959950204075'
